### ISSUE TITLE
Applovin Banner. Touch zone issue

### ISSUE THREAD

**Issue by Dima107** [distriqt/ANE-Adverts-Mediation#11]
I created Banner view: AdSize.BANNER.
When Applovin banner is displayed Touch zone is much bigger than banner. Also "i" button has wrong position
I added some comments to then screenshot
![applovin banner](https://user-images.githubusercontent.com/1449963/82417763-b1594680-9a84-11ea-9c69-3b049d35d3b0.jpg)

**Comment by marchbold** [comment]
Please try using either smart or adaptive banner sizing.

Banner size are a specific size and may not stretch to fill the correct area.

**Comment by Dima107** [comment]
SMART_BANNER  has no test fill: I didn't receive any test or real banner from Facebook and Applovin. 
One time I recived SMART_BANNER test ad from facebook and other issue happens. That banner wasn't SMART_BANNER, it was BANNER. So I had problem: adView.size was incorrect:
![banner](https://user-images.githubusercontent.com/1449963/82432863-4fefa280-9a99-11ea-9b9a-c23a2779d9ae.jpeg)

Adaptive I didn't try it yet. I'm afraid we'll have problems with fill for custom size banners

**Comment by Dima107** [comment]
I have issue with Applovin banner only

**Comment by marchbold** [comment]
If you use the banner size you must specify a viewport that matches the size of a banner. Doing anything different will present view issues.

**Comment by Dima107** [comment]
we don't use Apllovin Mediation
So I close this issue
