### ISSUE TITLE
How to integrate Facebook mediation to iOS and Android

### ISSUE THREAD

**Issue by shaymolho** [distriqt/ANE-Adverts-Mediation#13]
Hi @marchbold ,

Didn't quite understand from the documentation how to integrate facebook audience into iOS (not sure regarding Android too).

In the documentation you write:
Add the Frameworks folder to your application package, ensuring the dynamic FBAudienceNetwork.framework is included along with the swift libraries (dylib files).

What does it mean?
copying the folder will all its subfolders and files in to the application package (where the app manifest resides)? is that it?
the folder is full with uncompiled h files. 

Regarding Android,
In the documentation you write:
Add the audience_network.dex file to the root of your application package. (This file is located in the repository, this must be the same version as the extension).
Is that mean only copying the file near the manifest? i don't need to add it to the ADT package command?

Thanks
Shay

**Comment by marchbold** [comment]
So you need something like the following structure:

![Screen Shot 2020-06-18 at 6 15 36 pm](https://user-images.githubusercontent.com/442356/84995742-ba2a5e80-b18f-11ea-8bb1-3cb8033edf62.png)

The `audience_network.dex` file needs to be packaged with your android application 
and the `Frameworks` folder with your iOS application. Both at the root level, i.e. not in a subdirectory of your application package.

**Comment by shaymolho** [comment]
Ok, 
Thanks!
