### ISSUE TITLE
Facebook Audience Network needs update

### ISSUE THREAD

**Issue by Dima107** [distriqt/ANE-Adverts-Mediation#15]
Audience Network SDK 5.10.1 - July 17, 2020
Bug fixes
Fixed java.lang.NoClassDefFoundError: com.facebook.ads.redexgen.X.8O on some Android 4.x and 5.x builds.

We have high rate of this bug into our project. Is this possible to update your FacebookAudience.ane to version 5.10.1 at least?

https://developers.facebook.com/docs/audience-network/changelog-android#5_10_1

**Comment by marchbold** [comment]
The version we had released was the most recent that worked with AIR, we are awaiting a few fixes in order to be able to use the latest release. Will add this to our schedule and check in with Harman again.

**Comment by Dima107** [comment]
Thanks
We wait for new released
