### ISSUE TITLE
Facebook Audience network crash ios App on start

### ISSUE THREAD

**Issue by shaymolho** [distriqt/ANE-Adverts-Mediation#16]
Hi @marchbold ,

We're trying to integrate facebook mediation.
we succeeded to do so on Android, everything works fine,
but on iOS soon as i'm adding the extension to the app descriptor the build succeed but the app crashes immediately on launch.

I tried to remove all other ANEs and keep only Adverts and Facebook Audience mediation but the app still crashes on launch.

Looking on the ios console log i don't see any hints explaining the problem.

I'm attaching the ios console log,
app name is: com.wizits.buddiesStagingQa

[ios_console_log.txt](https://github.com/distriqt/ANE-Adverts-Mediation/files/5201007/ios_console_log.txt)

Thanks,
Shay

**Comment by marchbold** [comment]
Nothing stands out in the logs, could you post the crash report as well? 

Did you add the `GADApplicationIdentifier` key to your info additions, i.e. does Adverts work without the Facebook Audience mediator?

**Comment by shaymolho** [comment]
Hi @marchbold 

I do have a GADApplicationIdentifier, and Adverts work on production without any problem without the Facebook Audience mediator.

Attaching the crash report,
This have more data - maybe you can find the problem with that:
[SlotagramApplication-2020-09-13-160159.txt](https://github.com/distriqt/ANE-Adverts-Mediation/files/5214126/SlotagramApplication-2020-09-13-160159.txt)


I have a question regarding the implementation:
I've added the `Frameworks` folder under the build folder, do i need to do anything else with this folder and its files?

Thanks,
Shay

**Comment by marchbold** [comment]
The crash implies you aren't packaging the FBAudienceNetwork.framework in your application. 

You need to make sure it is included with your build, not just in the build directory but that the Frameworks directory is included in the package command.

**Comment by shaymolho** [comment]
OK
Can you explain how to so?

This is my package command:

```
-package -target 'ipa-ad-hoc'
-useLegacyAOT yes
-provisioning-profile 'D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2/config/buddies/Buddies_staging_qa.mobileprovision'
-storetype PKCS12
-keystore 'D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2/config/Slotagram_dev.p12'
-storepass 'password'
'buddies-mobile-boot.ipa'
slotagram-mobile-boot-app-ios.xml
slotagram-mobile.swf
-C D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2/target Frameworks
-C D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2/target assets
-C D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2/src/main/resources/buddies/root_ios .
-extdir .
```

I've added this line to add the Facebook frameworks:
`-C D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2/target Frameworks`

and this is the error i got:
`Error: FBAudienceNetwork.framework does not have an executable`

What is the correct way to do so?

**Comment by marchbold** [comment]
Sounds like you have a corrupted framework, try downloading it again from the repository?

**Comment by shaymolho** [comment]
Hi @marchbold 
You were right. For some reason some of the files were not copied to the build directory.

Fixed it, and build succeed. then I resigned the app,
And everything is working.
Superb!

Closing the issue
Thank you
