### ISSUE TITLE
[Question] SDK update plan

### ISSUE THREAD

**Issue by arcreature7** [distriqt/ANE-Adverts-Mediation#18]
Hi,

Are there any plans to update Facebook Audience and App Lovin SDK?
I need the latest version of the SDK to be able to use AdMob's open bidding beta feature.

[iOS]
 - Facebook adapter minimum version: 5.10.0.0
 - Applovin adapter minimum version: 6.3.0.0

[Android]
 - Facebook adapter minimum version: 5.10.0.0
 - Applovin adapter minimum version: 9.4.2.0

Could you tell me when it will be updated to the latest version?

**Comment by marchbold** [comment]
Apologies, I missed this question.

I'll have a look over these mediators this week and get them updated for you.
