### ISSUE TITLE
Sample Tutorial ?

### ISSUE THREAD

**Issue by flashomer** [distriqt/ANE-Adverts-Mediation#2]
Hi, Is there any admob sample tutorial that I can see?
sample_admob.as and demo_adverts.ane for we can try it

**Comment by marchbold** [comment]
Hi,

There is an example for mediation and using Admob in this repository:

https://github.com/distriqt/ANE-Adverts-Mediation/blob/master/example/applovin/simple/src/TestAppLovin.as

You can see the documentation for the Adverts ANE here:

- Development guide: https://distriqt.github.io/ANE-Adverts/
- Asdocs: http://distriqt.github.io/ANE-Adverts/asdocs/

Further information : https://airnativeextensions.com/extension/com.distriqt.Adverts

**Comment by flashomer** [comment]
oke but there are not a sample Adverts.ane

**Comment by marchbold** [comment]
No there is not a trial ANE currently available.

**Comment by flashomer** [comment]
oke, however, I need to see it worked to buy it.
How can we do that?

**Comment by marchbold** [comment]
Please contact our team at airnativeextensions@distriqt.com 

This is not really the correct place for this conversion.

**Comment by flashomer** [comment]
oke, thanks for informations 👍
