### ISSUE TITLE
Upgrade AppLovin SDK to at least 9.14.8

### ISSUE THREAD

**Issue by mwelk** [distriqt/ANE-Adverts-Mediation#20]
It would be nice if the AppLovin SDK could be upgraded to at least version 9.14.8.
We get the following notice while initalizing the SDK:

```
[AppLovinSdk] Current SDK version (9.13.4) is outdated. Please integrate the latest version of the AppLovin SDK (9.14.8). Doing so will improve your CPMs and ensure you have access to the latest revenue earning features.
```

**Comment by marchbold** [comment]
Will get this into our schedule.

**Comment by marchbold** [comment]
Just FYI, we will be releasing an update for this shortly but the currently maximum supported version with AdMob is 9.14.6
