### ISSUE TITLE
UILaunchImage shown after IronSource Video did closed on iOS

### ISSUE THREAD

**Issue by mwelk** [distriqt/ANE-Adverts-Mediation#24]
With IronSource we experience the following strange behaviour:

1. user starts video ad
2. application launch image visible for a very short time
3. video ad starts playing
4. video ad did finish
5. user closes video ad
6. application visible for a very short time
7. application launch image appears and keeps staying

application launch image is the image defined in:
```
<iPhone>
        <InfoAdditions>
            <![CDATA[
                <key>UILaunchImages</key>
                <array>
                    <dict>
                        <key>UILaunchImageName</key>
                        <string>Default-568h</string>
                        <key>UILaunchImageSize</key>
                        <string>{320, 568}</string>
                    </dict>
                </array>
            ]]>
        </InfoAdditions>
</iPhone>
```
Test-Ads or other adapters work fine.

AIR: 33.1.1300
OS: iOS 12.4.9
ANE-Adverts: 10.1.037
ANE-Adverts-Mediation: 5.1.0

**Comment by marchbold** [comment]
Does this occur if you use the new launch storyboard instead?

**Comment by mwelk** [comment]
Did not heard about storyboard yet ;-) I have to find out how to use it first...

**Comment by marchbold** [comment]
It is a requirement now so you should definitely move to it asap.

**Comment by mwelk** [comment]
Ok, app is now using storyboard but the behaviour stays the same for IronSource.

**Comment by marchbold** [comment]
So after an IronSource ad mediated through AdMob your app is no longer visible, you only see the launch storyboard?

**Comment by mwelk** [comment]
Yes.

**Comment by marchbold** [comment]
Okay, will have to investigate this one, seems like it must be an issue in the ironsource / admob implementation though as we don't control that aspect of the display on iOS. 

If you find any other references / bug reports on the web please let us know.

**Comment by marchbold** [comment]
Could you verify this is still happening with the latest SDK version?
