### ISSUE TITLE
Audience Network SDK For iOS14

### ISSUE THREAD

**Issue by everseen83** [distriqt/ANE-Adverts-Mediation#25]
Hello :)

The Facebook Audience Network warned with the following information:

> All publishers will need to use Audience Network SDK 6.2.1 in order to monetize with iOS 14 users when Apple introduces their new requirements. 

https://developers.facebook.com/blog/post/2020/10/29/preparing-our-partners-ios-14-latest-guidance-on-skadnetwork/

Please review the issue.

Thank you always.

**Comment by marchbold** [comment]
We will be updating the mediators soon.
