### ISSUE TITLE
TapJoy mediation

### ISSUE THREAD

**Issue by Mintonist** [distriqt/ANE-Adverts-Mediation#26]
Hi!
Is it possible to add TapJoy mediation for ADMob?
You have done it for IronSource.
Thx!

**Comment by marchbold** [comment]
Yep, will get this into development.

**Comment by marchbold** [comment]
Here's a beta if you wouldn't mind testing it for us? 

https://www.dropbox.com/s/rrlk0b7097ybzj8/com.distriqt.AdvertsMediation.v5.2.0.zip?dl=0
