### ISSUE TITLE
Build error adding TapJoy mediation

### ISSUE THREAD

**Issue by mwelk** [distriqt/ANE-Adverts-Mediation#27]
When adding the com.distriqt.admob.TapJoy extension the build fails with the following error:

```
aapt tool failed:ERROR: Unable to open class file C:\...\con\tapjoy\Manifest.java: No such file or directory
```

Platform and lib versions:
AIR: 33.1.1.345
ANE-Adverts: 12.0.009
ANE-Adverts-Mediation: v5.3.0
Build-OS: Windows 10

**Comment by marchbold** [comment]
That path looks very odd, can you elaborate on your build process and what other ane's etc you may have ?

**Comment by mwelk** [comment]
The error message appears only while adding the TapJoy ane. The path was shorten by me for the issue reporting but the "con\tapjoy\Manifest.java" is still weird.

We have a lot of other ANE's in this project:

com.distriqt.Application: 6.5.051
com.distriq.Firebase: 6.0.003
com.distriqt.Core: 6.3.023
androidx.core: 1.5.0
androidx.appcompat: 1.5.0
androidx.browser: 1.5.0
androidx.cardview: 1.5.0
androidx.recyclerview: 1.5.0
androidx.transition: 1.5.0
androidx.constraintlayout: 1.5.0
androidx.vectordrawable: 1.5.0
androidx.multidex: 1.5.0
androidx.room: 1.5.0
androidx.work: 1.5.0
com.google.android.material: 1.5.0
com.google.android.datatransport: 1.5.0
com.google.dagger: 1.5.0
com.google.protobuflite: 1.5.0
com.google.guava: 1.5.0
com.google.code.gson: 1.5.0
io.grpc: 1.5.0
io.reactivex: 1.5.0
com.android.installreferrer: 1.5.0
com.google.firebase.core: 26.3.0
com.google.android.play: 26.3.0
com.distriqt.playservices.Base: 26.3.0
com.distriqt.playservices.Auth: 26.3.0
com.distriqt.playservices.Identity: 26.3.0
com.distriqt.playservices.Ads: 26.3.0
com.distriqt.playservices.AdsIdentifier: 26.3.0
com.distriqt.playservices.CloudMessaging: 26.3.0
com.distriqt.firebase.Auth: 6.0.003
com.distriqt.firebase.RemoteConfig: 6.0.003
com.distriqt.firebase.Crashlytics: 6.0.003
com.distriqt.firebase.Performance: 6.0.003
com.distriqt.firebase.DynamicLinks: 6.0.003
com.distriqt.square.okhttp: 4.0.001
com.distriqt.square.okhttp3: 4.0.001
com.distriqt.square.picasso: 4.0.001
com.distriqt.Adverts: 12.0.009
com.distriqt.admob.IronSource: 5.3.0
com.distriqt.admob.UnityAds: 5.3.0
com.distriqt.admob.AppLovin: 5.3.0
com.distriqt.admob.FacebookAudience: 5.3.0
com.distriqt.admob.TapJoy: 5.3.0
com.distriq.RestartApp: 3.0.013
com.distriq.InAppBilling: 13.0.037
com.distriqt.facebook.Core: 9.0.011
com.distriqt.facebook.Login: 9.0.011
com.distriqt.Bolts: 4.1.033
com.distriqt.GoogleIdentity: 5.2.002
com.distriqt.Dialog: 8.4.094
com.distriqt.PushNotifications.FCM: 10.2.043
com.distriqt.NetworkInfo: 4.1.010
com.distriqt.NativeWebView: 5.2.378
com.distriqt.AppleSignIn: 2.2.088
com.distriqt.Share: 7.0.008
com.distriqt.Memory: 4.0.009
com.distriqt.IDFA: 5.0.028
com.distriq.ApplicationRater: 6.0.011

**Comment by marchbold** [comment]
What version of Java are you using?

**Comment by mwelk** [comment]
It's the same with version **1.8.0_211** and **1.8.0_241**

**Comment by marchbold** [comment]
Bit lost, not sure what to suggest here.

**Comment by marchbold** [comment]
Just to confirm this error appears only after adding the `com.distriqt.admob.TapJoy` extension to your application and the associated manifest additions? ie no other changes?

**Comment by mwelk** [comment]
Yes, no other additions.

**Comment by marchbold** [comment]
Can you elaborate on your build process?

**Comment by mwelk** [comment]
There is nothing special. We use [gradlefx](http://gradlefx.org/) to build the application.

**Comment by marchbold** [comment]
Okay, just I can't replicate this issue. Have you tried building without using gradlefx?

**Comment by mwelk** [comment]
No, not yet, but I will try it.

**Comment by mwelk** [comment]
Same result :-(
I searched in the ANE package for **con.tapjoy** from the error report and found it in the platform.xml files of the Android directories.
It looks lie a typo and **ADT** is not able to resolve this package name.

**Comment by mwelk** [comment]
Just changed the **con.tapjoy** to **com.tapjoy** in the platform.xml files inside the ANE and now it's building again.

**Comment by marchbold** [comment]
Hmmm apologies appears we have a build in testing that has fixed that issue and I was testing with that. 

I'll roll out this latest round of updates today.

**Comment by mwelk** [comment]
Great, thanks!
