### ISSUE TITLE
FAN. setAdvertiserTrackingEnabled method

### ISSUE THREAD

**Issue by Dima107** [distriqt/ANE-Adverts-Mediation#28]
I found it in as3docs.
But I didn't find usage of it in example and implementation guide. 
Is this method required for correct implementation?

**Comment by marchbold** [comment]
This is for usage in the case where you wish to disable automatic tracking and request authorisation from your users before enabling it. 

https://developers.facebook.com/docs/audience-network/guides/advertising-tracking-enabled/

**Comment by ventr1x** [comment]
Are you calling this internally with true automatically?
It has to be manually called before init according to Facebook.

**Comment by marchbold** [comment]
The extension does not call this automatically.
