### ISSUE TITLE
Logs show a possible problem

### ISSUE THREAD

**Issue by shaymolho** [distriqt/ANE-Adverts-Mediation#30]
My code:
```
Adverts.service.setup(AdvertPlatform.PLATFORM_ADMOB);
Adverts.service.addEventListener(AdvertsEvent.INITIALISED, initialisedHandler);
Adverts.service.addEventListener(ErrorEvent.ERROR, errorHandler);
Adverts.service.initialise();
AdMobIronSource.instance.init();
AdMobUnityAds.instance.setConsent(true);
AdMobIronSource.instance.setConsent(true);

function initialisedHandler( event:AdvertsEvent ):void 
{
    for each (var adapterStatus:AdapterStatus in e.adapterStatus)
    {
        trace( "adapter: " + adapterStatus.name + " : " + adapterStatus.state + " [" + adapterStatus.latency + "] - " + adapterStatus.description );
    }
}
```
As written [in the docs](https://docs.airnativeextensions.com/docs/adverts/initialise-platform/)

I see the following logs:
```
2021/06/10 12:53:08.759  [INFO] [ScriptClass ModulesMobileAdvertsService] - adapter: com.google.android.gms.ads.MobileAds : READY [5] - 
2021/06/10 12:53:08.760  [INFO] [ScriptClass ModulesMobileAdvertsService] - adapter: com.google.ads.mediation.facebook.FacebookMediationAdapter : READY [932] - 
2021/06/10 12:53:08.760  [INFO] [ScriptClass ModulesMobileAdvertsService] - adapter: com.google.ads.mediation.ironsource.IronSourceMediationAdapter : NOT_READY [879] - Failed to initialize adapter. com.google.ads.mediation.ironsource.IronSourceMediationAdapter does not implement the initialize() method.
2021/06/10 12:53:08.761  [INFO] [ScriptClass ModulesMobileAdvertsService] - adapter: com.google.ads.mediation.unity.UnityMediationAdapter : NOT_READY [3130] - 111: Missing or Invalid Game ID.
2021/06/10 12:53:08.761  [INFO] [ScriptClass ModulesMobileAdvertsService] - Adverts Initialized Completed
```
What do these line mean and how to resolve those issues?
logcat file attached:
[ad_network_tracing.txt](https://github.com/distriqt/ANE-Adverts-Mediation/files/6630490/ad_network_tracing.txt)

**Comment by marchbold** [comment]
Thanks for reporting this, it may be related to #29 which we are looking into as well. 

Can you post the complete logs or make sure you include distriqt in your filter

**Comment by shaymolho** [comment]
[Uploading full_network_tracing.txt…]()

**Comment by marchbold** [comment]
Could you try this build for me:

https://www.dropbox.com/s/b50qc3wf2abiybr/com.distriqt.Adverts-IronSource.v7.1.013.zip?dl=0

**Comment by shaymolho** [comment]
With this build the app crashes on loading.
Logs attached.
[network_tracing.txt](https://github.com/distriqt/ANE-Adverts-Mediation/files/6682315/1234.txt)

**Comment by marchbold** [comment]
Could you try adding the `com.jetbrains.kotlin` ane from Android support?

https://github.com/distriqt/ANE-AndroidSupport/raw/master/lib/com.jetbrains.kotlin.ane

**Comment by shaymolho** [comment]
I saw that 
<provider
    android:name="com.ironsource.lifecycle.IronsourceLifecycleProvider"
    android:authorities="APPLICATION_PACKAGE.IronsourceLifecycleProvider" />
is in the docs
but not in the example. Is that on purpose? Should I include it in my xml?

**Comment by shaymolho** [comment]
Also, I see this message when building apk:

>      [exec] An implementation for native extension 'com.jetbrains.kotlin.ane' required by the application was not found for the target platform.

Can you advise on it?

**Comment by marchbold** [comment]
Try removing the `.ane` from the end of the extension id in your application descriptor. 

The lifecycle provider appears to have been removed from the latest release of ironsource so it's no longer needed. You should just have 3 additional activities for ironsource.  

```xml
        <activity
            android:name="com.ironsource.sdk.controller.ControllerActivity"
            android:configChanges="orientation|screenSize"
            android:exported="false"
            android:hardwareAccelerated="true" />
        <activity
            android:name="com.ironsource.sdk.controller.InterstitialActivity"
            android:configChanges="orientation|screenSize"
            android:exported="false"
            android:hardwareAccelerated="true"
            android:theme="@android:style/Theme.Translucent" />
        <activity
            android:name="com.ironsource.sdk.controller.OpenUrlActivity"
            android:configChanges="orientation|screenSize"
            android:exported="false"
            android:hardwareAccelerated="true"
            android:theme="@android:style/Theme.Translucent" />
```

**Comment by shaymolho** [comment]
```
2021/06/22 11:54:33.028  [INFO] [ScriptClass ModulesMobileAdvertsService] - adapter: com.google.android.gms.ads.MobileAds : READY [2] - 
2021/06/22 11:54:33.029  [INFO] [ScriptClass ModulesMobileAdvertsService] - adapter: com.google.ads.mediation.facebook.FacebookMediationAdapter : READY [800] - 
2021/06/22 11:54:33.030  [INFO] [ScriptClass ModulesMobileAdvertsService] - adapter: com.google.ads.mediation.ironsource.IronSourceMediationAdapter : READY [748] - 
2021/06/22 11:54:33.030  [INFO] [ScriptClass ModulesMobileAdvertsService] - adapter: com.google.ads.mediation.unity.UnityMediationAdapter : NOT_READY [2416] - 111: Missing or Invalid Game ID.
```
Now IronSource is okay. Do you know how to resolve 

> 2021/06/22 11:54:33.030  [INFO] [ScriptClass ModulesMobileAdvertsService] - adapter: com.google.ads.mediation.unity.UnityMediationAdapter : NOT_READY [2416] - 111: Missing or Invalid Game ID.

Thanks for the support

**Comment by marchbold** [comment]
Can you open a new issue for the unity ads extension and we'll look into it, generally I believe that should be retrieved from the server, so could mean your account isn't setup completely for unity ads?
