### ISSUE TITLE
Facebook Audience Network crash on Android

### ISSUE THREAD

**Issue by mwelk** [distriqt/ANE-Adverts-Mediation#31]
After upgrading to latest Adverts and Mediation ANE's we get a lot of following crashes in the Facebook Audience Network adapter:
```
backtrace:
  #00  pc 000000000058f8d4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+208)
  #00  pc 0000000000130a14  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20)
  #00  pc 0000000000abb298  /data/app/air.com.smeet.smeetmobile-r-UwgDNHEn-TYNa4HwU4pQ==/oat/arm64/base.vdex (com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.doCallInitialize+80)
  #00  pc 0000000000593ff8  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStaticRange+768)
  #00  pc 0000000000130c94  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static_range+20)
  #00  pc 0000000000abb230  /data/app/air.com.smeet.smeetmobile-r-UwgDNHEn-TYNa4HwU4pQ==/oat/arm64/base.vdex (com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.access$200)
```

If I interpret the `lib/facebookaudience/Version.md` => `| com.distriqt.admob.FacebookAudience | 6.2.009 | 6.4.0 | 6.5.0 |` right then the `6.4.0` is the Android SDK version and `6.5.0` is the iOS SDK version.

Facebook fixed a [bug](https://developers.facebook.com/support/bugs/208906161009896/) in `6.5.0` which looks like this one.

Could you please update the Android SDK to version 6.5.0?

Envrionment settings:
OS: Android
AIR: 33.1.1.444
ANE-Adverts: 6.5.056
ANE-Adverts-Mediation: 6.0.0

**Comment by marchbold** [comment]
I'll look into getting it updated as soon as we can.

**Comment by marchbold** [comment]
Here's the beta for v6.5.0 of facebook audience on android.

Could you let me know how it goes?

https://www.dropbox.com/s/n7xys04bilr4p1t/com.distriqt.Adverts-Facebook.v6.3.001.zip?dl=0

(make sure you update the audience network.dex file)

**Comment by everseen83** [comment]
"The beta for v6.5.0 of facebook audience on android"
This works well for me :)

**Comment by marchbold** [comment]
Great to hear it's working.

With your note, do you mean this: https://docs.airnativeextensions.com/docs/adverts/mediation/facebookaudience#android

**Comment by everseen83** [comment]
Which of the two should be used for the code in the android manifest? "Sample" or "documentation"?

**Comment by marchbold** [comment]
What are you referring to by "sample"? Do you mean the example application?  Either, but obviously the example application has real/test values in it.

**Comment by marchbold** [comment]
The docs, will not have been updated to the latest release though so will potentially be missing some references currently.

**Comment by everseen83** [comment]
Yes, I mean "Example" :)

- example code - 
```
            <activity
                android:name="com.facebook.ads.AudienceNetworkActivity"
                android:configChanges="keyboardHidden|orientation|screenSize"
                android:exported="false"
                android:theme="@android:style/Theme.Translucent.NoTitleBar" />

            <provider
                android:name="com.facebook.ads.AudienceNetworkContentProvider"
                android:authorities="air.net.ideasam.games.cat.AudienceNetworkContentProvider"
                android:exported="false" />

            <activity
                android:name="com.facebook.ads.internal.ipc.RemoteANActivity"
                android:configChanges="keyboardHidden|orientation|screenSize"
                android:exported="false"
                android:process=":adnw"
                android:theme="@android:style/Theme.Translucent.NoTitleBar" />

            <service
                android:name="com.facebook.ads.internal.ipc.AdsProcessPriorityService"
                android:exported="false" />
            <service
                android:name="com.facebook.ads.internal.ipc.AdsMessengerService"
                android:exported="false"
                android:process=":adnw" />
```

- docs code - 
```
<activity
    android:name="com.facebook.ads.AudienceNetworkActivity"
    android:configChanges="keyboardHidden|orientation|screenSize"
    android:exported="false"
    android:theme="@android:style/Theme.Translucent.NoTitleBar" />

<provider
    android:name="com.facebook.ads.AudienceNetworkContentProvider"
    android:authorities="APPLICATION_PACKAGE.AudienceNetworkContentProvider"
    android:exported="false" />
```

> The docs, will not have been updated to the latest release though so will potentially be missing some references currently.

Ok, I got it!

**Comment by marchbold** [comment]
Yeah, so use the example in this case as it's a beta, I'll get the docs updated when we release.  But yes you still will need to modify the additions as per the docs.

**Comment by mwelk** [comment]
Hi Michael, thanks for the update.
We will test it this week.
