### ISSUE TITLE
Facebook Audience ane size

### ISSUE THREAD

**Issue by mucoci** [distriqt/ANE-Adverts-Mediation#34]
Hi
The new Updated - Facebook Audience ane v6.6.0 is 48MB?
Because the last version is only 8 mb...

This is a huge changing

**Comment by marchbold** [comment]
Hi,

We have been able to bring the Facebook Audience mediation ANE inline with the other mediation ANEs, and are now statically linking the Facebook SDK. This means you can remove the dynamic frameworks in the Frameworks folder.

See the note here:

https://docs.airnativeextensions.com/docs/adverts/mediation/facebookaudience/#ios

This should make usage of the ANE simpler. The actual size change to your application shouldn't be much at all, if any.

**Comment by mucoci** [comment]
Nice!

It is really easy to use it in iOS!
Tthanks, guys

**Comment by marchbold** [comment]
That increase is probably inline with the update from 6.5 - 6.6 as well. Facebook finally corrected their static builds of this framework so it's good to be able to use it like this again!
