### ISSUE TITLE
Unity Ads not working [Android]

### ISSUE THREAD

**Issue by everseen83** [distriqt/ANE-Adverts-Mediation#35]
Adverts  = 13.3.31 | 13.2.013
AdvertsMediation = 6.2.1
Device : Nexus5, LG G6

Hello there!
After updating the AdvertsMediation-ANE, The following error message occurs.

**com.google.ads.mediation.unity.UnityMediationAdapter : NOT_READY [1] - Failed to create Adapter.**

Thanks :)

**Comment by marchbold** [comment]
Can you post the logs from the device you are testing on ?

https://docs.airnativeextensions.com/docs/tutorials/device-logs

**Comment by everseen83** [comment]
Sure.
[Nexus5.txt](https://github.com/distriqt/ANE-Adverts-Mediation/files/7166376/Nexus5.txt)

**Comment by marchbold** [comment]
Have you updated all the androidx dependencies as well? Looks as though there are some errors around one of the androidx libs.

**Comment by everseen83** [comment]
Yes. Even if all libraries are updated to the latest, the same error occurs.

**Comment by marchbold** [comment]
Okay, and you are definitely packaging the unity mediator with your app and have the manifest additions?

**Comment by everseen83** [comment]
Yes. It worked fine until I updated the library.

**Comment by marchbold** [comment]
Hmmm okay, I'll run some more tests on the update today and see if I can spot anything.

**Comment by marchbold** [comment]
We have checked the build and it isn't a simple build issue, I believe there is some issue in the builds AdMob released. We are updating all the mediators and admob sdk to the latest and will see if this issue is resolved there.

**Comment by marchbold** [comment]
Could you try the following version for us?

[com.distriqt.admob.UnityAds.ane.zip](https://github.com/distriqt/ANE-Adverts-Mediation/files/7535855/com.distriqt.admob.UnityAds.ane.zip)

**Comment by Dima107** [comment]
At this moment
com.google.ads.mediation.unity.UnityMediationAdapter : READY [5027]
I'll tell you later if all types of ads works good

**Comment by Dima107** [comment]
Can we use this version for store build?

**Comment by marchbold** [comment]
Yes, but I will do an official release towards the end of the week.
