### ISSUE TITLE
queries tag in xml

### ISSUE THREAD

**Issue by mucoci** [distriqt/ANE-Adverts-Mediation#36]
Hi

I have updated the latest FacebookAudience.ane
and I found it need to add queries tag in xml (Android)

But is shows the Android not support queries now

Then I found a discussion here(you and ajwfrost , the content is this queries tag)
https://github.com/airsdk/Adobe-Runtime-Support/issues/1100

But I don't know how to change this new adt.jar in the link
(I am not familiar with adt command)

My question is :
Can I delete this queries tag before new Air SDK release?
I have released a new version app with latest FacebookAudience.ane yesterday, but I forget add this queries tag)
it seems to runs well~

**Comment by marchbold** [comment]
Hi,

Generally the queries tags will affect the ability to check for installed applications on Android 30+. So you may be able to operate most of the functionality in the facebook audience mediation relatively well without them. 

They will become much more common across extensions with Android 30 specific updates rolling out across the SDKs. 

I believe the latest release of AIR has this update included but I haven't had a chance to confirm yet.

**Comment by mucoci** [comment]
Haha

I just found that there is a new Air SDK (33.1.1.620) yesterday~
in this new version
the issue about queries tag have been solved!

**Comment by marchbold** [comment]
Yeah great! 

Was due to roll out, which is why we started releasing ANEs with this requirement .

Cheers
