### ISSUE TITLE
[FAN] ios/Frameworks folder - no longer necessary?

### ISSUE THREAD

**Issue by everseen83** [distriqt/ANE-Adverts-Mediation#39]
When installing Facebook Audience Network using APM, the "ios/Frameworks" folder is not created.
Is the "resign" process no longer necessary?

In the document, it is explained as follows, so it is confusing.😅
> You will have an assets directory that contains required assets for the installed extensions. You must add the files in the assets/android folder to the root of your Android application package and the assets/ios folder to the root of your iOS application package. (The android folder contains the audience_network.dex file that is required on Android and the ios folder contains a Frameworks folder with the required iOS dynamic frameworks).

**Comment by marchbold** [comment]
I'll check into this, I thought it should have still been a dynamic framework.

**Comment by marchbold** [comment]
Apologies, seems something went wrong with our build and this framework was excluded. I'm getting it updated now and will release the update shortly.

**Comment by everseen83** [comment]
Thanks!

Also, the **audience_network.dex** file in the sample project and the file downloaded by apm seem to be different.
Please check that.

**Comment by marchbold** [comment]
Hi, yes the dex file was updated too. Cheers

**Comment by mwelk** [comment]
When will the updates be published to the apm repository?

**Comment by marchbold** [comment]
They should be available now as well. Let me know if you are having issues with them.
