### ISSUE TITLE
Different Mediation network

### ISSUE THREAD

**Issue by megajogos** [distriqt/ANE-Adverts-Mediation#4]
Hello Distriqt,

I need to implement mediation via another network instead of AppLovin https://github.com/distriqt/ANE-Adverts-Mediation/wiki/AppLovin the network you made an adapter.

I Need to imlement these networks:
- AdColony
- UnityAds
- Chartboost 
- Vungle

Is it possible to implement it with your libs?

**Comment by marchbold** [comment]
Hi 

We don't currently have mediators for those networks available. If you need them you can either contact our custom development team (airnativeextensions@distriqt.com) or add enhancement requests for them here and we'll attempt to get them into our development schedule.

Cheers.
