### ISSUE TITLE
New mediation network: Pangle Ad Network

### ISSUE THREAD

**Issue by megajogos** [distriqt/ANE-Adverts-Mediation#44]
Would be nice to use this mediation network: Pangle Ad Network

Could you add support to this network?

**Comment by marchbold** [comment]
I'll look into adding it

**Comment by megajogos** [comment]
Any news?

**Comment by marchbold** [comment]
We haven't had time to look into adding this as yet.

**Comment by megajogos** [comment]
Any updates?

**Comment by marchbold** [comment]
Still at the same stage unfortunately, we have been super busy of late.

**Comment by funyamora** [comment]
I too think it would be great if Pangle could be used.
Pangle is a fairly profitable and important ad network in the Asian region.
I know you are busy, but I hope you will consider this when you can spare the time.
