### ISSUE TITLE
[FAN] Crash on startup in iOS

### ISSUE THREAD

**Issue by everseen83** [distriqt/ANE-Adverts-Mediation#45]
Hello, again.

The following crash occurs in the latest version of "FacebookAudience(version 6.11.0)"
However, using an older version of the Frameworks folder does not crash.

##### Environment 

- AIR SDK version: 33.1.1.889
- Device OS: iPhone OS 12.0.1
- Device version: iPhone8,1
- Development IDE: VS code
- Development OS: OSX

##### Logs
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Library not loaded: @rpath/libswiftCore.dylib | Referenced from: /private/var/containers/Bundle/Application/E1E58B7A-4789-4C74-B35E-E6F92BB648E8/TheCat.app/Frameworks/FBAudienceNetwork.framework/FBAudienceNetwork | Reason: image not found

**Comment by marchbold** [comment]
What version of the swift dylibs are you including in your application? You need to include them to support < iOS 12.2

**Comment by everseen83** [comment]
Could you please tell me where I can find the version for it?

Meanwhile,  do I have to manually add swift dylibs?

**Comment by marchbold** [comment]
Yes, for iOS 12.2 or less. Personally we set that as the minimum for our apps now to avoid this requirement as it increases app size significantly. 

Probably easiest to tell the version if you check where you got the libs from.

**Comment by everseen83** [comment]
Thanks for your answer.
So far, I have never manually added "swift dylibs" to my application.
Any instructions on manually adding swift dylibs?

[Crashed on the version below]
ANE-Adverts-Mediation-master [v6.4.0]

**Comment by marchbold** [comment]
You just basically have to add them to your frameworks directory along with the dynamic frameworks. 

I'll see if I can get the required ones for you.

**Comment by marchbold** [comment]
Can you try adding this version, I believe these are all the ones you need. You need to add these files into your "Frameworks" folder.

https://drive.google.com/file/d/1lugqX2B_QigdWiiK7bsnz_eiS__--Dpf/view?usp=sharing

**Comment by everseen83** [comment]
Okay :) 
Thanks for your support.
