### ISSUE TITLE
Big size of FAN adaper

### ISSUE THREAD

**Issue by Dima107** [distriqt/ANE-Adverts-Mediation#47]
Platform: IOS
Earlier IPA file was about 38 MB. 

Then I updated all ANEs in project. IPA size became 54 MB.

It's because of FAN. I know this because after removing FAN ane and dymamic libraries  IPA file size became 37 mb

Probably something wrong with dynamic libraries? It looks like size is too big

**Comment by marchbold** [comment]
What version of AIR are you using? The FBAudienceNetwork framework has increased by about 20mb since some of the older releases so this is potentially as expected.

**Comment by Dima107** [comment]
Latest - 33.1.1.929

**Comment by Dima107** [comment]
I tried 795. Size is big too.

**Comment by marchbold** [comment]
I'd say this is just due to the increase in size in the Facebook Audience network framework then. The size of this framework is outside our control.
