### ISSUE TITLE
Unity Ads initialization failed

### ISSUE THREAD

**Issue by megajogos** [distriqt/ANE-Adverts-Mediation#49]
Error initializating unity ads.

Logs:
```
2022-09-27 20:32:52.079 28530-28530/air.br.com.megajogos.mobile W/UnityMediationAdapter: {
      "Code": 301,
      "Message": "Unity Ads initialization failed for game ID '4027593' with error message: Unity Ads SDK failed to initialize due to previous failed reason",
      "Domain": "com.unity3d.ads",
      "Cause": "null"
    }
```

Maybe the distriqt must update the Unity SDK.

##### Environment 

- AIR SDK version: 33.1.1.889
- Device OS: Android

**Comment by marchbold** [comment]
Could you post the entire log? Seems to reference a previous error?

**Comment by megajogos** [comment]
I don't have the entire log now. But we have talked to unity support and they asked us to update the Unity SDK to 4.4.0.

Unity response:
```
Thanks for contacting Unity Ads Support!
 
I tried to run your project with Admob Test Suite, and I can't reproduce the error you sent earlier.
 
May I know if the issue consistently can be reproduced? 
Which version of Unity Ads SDK and Admob-Unity adapter are you using? Can you try out version 4.4.0 and check if the issue still exists?
Is it happen to a specific Ad unit ID?
 
Thanks.
Regards,
Chi Boon
Unity Services Support
```

Could you update the unity SDK?

**Comment by marchbold** [comment]
We will update the adapters with the next update of the sdk.

**Comment by megajogos** [comment]
Any news about this?

**Comment by marchbold** [comment]
The Android Unity SDK was updated to v4.5.0 in [v6.6.0](https://github.com/distriqt/ANE-Adverts-Mediation/blob/master/CHANGELOG.md) of the extensions, so this should be resolved? Let me know if you are still having issues. 

Grab the latest release [here](https://github.com/distriqt/ANE-Adverts-Mediation/releases) or via apm.

**Comment by marchbold** [comment]
Hi, We have identified the issue and will update the mediator shortly. Be aware that there will be a new dependency extension.
