### ISSUE TITLE
App Crashing! 

### ISSUE THREAD

**Issue by Shaunmax** [distriqt/ANE-Adverts-Mediation#50]
Hello,

After updating the ane my app is crashing :- please find the crash log below : -

10-18 17:13:03.030  9566  9566 D AndroidRuntime: Shutting down VM
10-18 17:13:03.031  9566  9566 E AndroidRuntime: FATAL EXCEPTION: main
10-18 17:13:03.031  9566  9566 E AndroidRuntime: Process: air.com.company.appname, PID: 9566
10-18 17:13:03.031  9566  9566 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at com.adcolony.sdk.c1.d(SourceFile:3)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at com.adcolony.sdk.j.i(SourceFile:7)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at com.adcolony.sdk.l$f.a(SourceFile:1)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at com.adcolony.sdk.l.b(Unknown Source:2)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at com.adcolony.sdk.i0$a.run(SourceFile:15)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at com.adcolony.sdk.z0.b(SourceFile:35)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at com.adcolony.sdk.i0.a(SourceFile:21)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at com.adcolony.sdk.k.L(SourceFile:1)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at com.adcolony.sdk.k.g(SourceFile:1)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at com.adcolony.sdk.k$o.run(SourceFile:1)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/~~l2-MWAGWlBLsvqpRzGN12Q==/air.com.company.appname-byViekFzCc_N0sM5WKh5Sg==/base.apk"],nativeLibraryDirectories=[/data/app/~~l2-MWAGWlBLsvqpRzGN12Q==/air.com.company.appname-byViekFzCc_N0sM5WKh5Sg==/lib/arm64, /data/app/~~l2-MWAGWlBLsvqpRzGN12Q==/air.com.company.appname-byViekFzCc_N0sM5WKh5Sg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-18 17:13:03.031  9566  9566 E AndroidRuntime: 	... 18 more

**Comment by marchbold** [comment]
Try adding the kotlin extension. Seems we may have missed them adding this dependency

apm install com.jetbrains.kotlin

I'll make sure the package gets updated.
