### ISSUE TITLE
Ads not ready

### ISSUE THREAD

**Issue by SponsorAds** [distriqt/ANE-Adverts-Mediation#51]
Since the new version, we constantly get support requests about ads not being displayed.
I could check this myself with Ironsrc. The plugin reports rewarded ad being ready (only then do we show any ad options). User Clicks on button.. aaand nothing. No error, no ad, no success message. 
logcat clearly indicates that there indeed was no ad ready at all (509 No ads to show), but no event handler gets anything in return. 

AIR: .929
Adverts: 13.7.5
IronSource: 7.2.5

The issue seems to be exclusively on Android, but I can't be sure about that as 90% of our users are Android.
We already fully deactivated IronSrc but still receive complaints after over a week.

**Comment by marchbold** [comment]
Any chance you can provide an adb logcat output from when this occurs?

**Comment by spAds2** [comment]
```
10-24 11:44:27.401 24167 24167 D com.distriqt.Adverts: GoogleAdMobRewardedVideoAd::[23e2d9d8-7286-4b2b-93e6-a0cbb9da65ce]:isLoaded()
10-24 11:44:28.046 24167 24167 E IronSourceMediationAdapter: IronSource failed to load rewarded ad for instance ID: 6367771. Error: Load failed - Failed to load RewardedVideo ad
10-24 11:44:28.053   658   658 I SurfaceFlinger: SFWD update time=67500849668911
10-24 11:44:28.078 24167 24167 D IronSourceMediationAdapter: Loading IronSource rewarded ad with instance ID: 6367773
10-24 11:44:28.078 24167 24167 E IronSourceMediationAdapter: An ad is already loading for instance ID: 6367773
```

I can send you the entire log through something less public, but there is not much else to see. No error or exception thrown, other mediations work on my tests, while users still report issues.

**Comment by marchbold** [comment]
Right, well that would indicate there is an issue in the mediation adapter or network somewhere outside of our control. Best I can do is check if there is an update to the ironsource adapter. 

Assuming you have checked you have set the correct account details etc in admob for ironsource mediation?
