### ISSUE TITLE
Compilation failed on iOS with Pangle

### ISSUE THREAD

**Issue by megajogos** [distriqt/ANE-Adverts-Mediation#53]
Logs:
```
ld: in /var/folders/ks/fsng9hxn5776jq_jmkfhk46w0000gp/T/149abd7b-8478-4df6-b167-4170f08955df/BUAdSDK.framework/BUAdSDK(BUAdSDKManager.o), could not parse object file /var/folders/ks/fsng9hxn5776jq_jmkfhk46w0000gp/T/149abd7b-8478-4df6-b167-4170f08955df/BUAdSDK.framework/BUAdSDK(BUAdSDKManager.o): 'Invalid bitcode version (Producer: '1300.0.29.3.0_0' Reader: '1200.0.32.29_0')', using libLTO version 'LLVM version 12.0.0, (clang-1200.0.32.29)' file '/var/folders/ks/fsng9hxn5776jq_jmkfhk46w0000gp/T/149abd7b-8478-4df6-b167-4170f08955df/BUAdSDK.framework/BUAdSDK' for architecture arm64

Compilation failed while executing : ld64
```
##### Environment 

- AIR SDK version: AIR 50.0.1.3.

**Comment by marchbold** [comment]
What version of Xcode etc do you have installed on your machine? Are you using native signing or the builtin AIR signing?

**Comment by marchbold** [comment]
Can you try updating Xcode?

**Comment by marchbold** [comment]
Try enabling native signing if you have the latest xcode build tools installed.

**Comment by megajogos** [comment]
Could you send me any documentation or tutorial that explain how to do that?

**Comment by marchbold** [comment]
Native signing? Just enable the "UseNativeCodesign" flag in your `adt.cfg` file. 

With 50 you can edit the user version at `~/.airsdk/adt.cfg` or use the new AIRSDKManager to enable it.
