### ISSUE TITLE
ITMS-90482: Invalid Executable

### ISSUE THREAD

**Issue by pitanello** [distriqt/ANE-Adverts-Mediation#55]
I tried to upload an .ipa with AIR 50.1.1.2 (Windows) and i got this message from Apple :

ITMS-90482: Invalid Executable - The executable 'Escape Prison.app/Frameworks/FBAudienceNetwork.framework/FBAudienceNetwork' contains bitcode.

In the new build i removed Facebook Audience Network and it is working fine, would it possible to fix this problem so i can put back Facebook in the bidding stack?
Thanks
Gaetano

**Comment by marchbold** [comment]
We have been waiting for a viable solution from Harman to update our extensions to support Xcode 14. We seem to have a partial solution now so will look into updating the extensions to support this in the new year.

**Comment by marchbold** [comment]
This has been completed
