### ISSUE TITLE
[iOS]Unable to package with Pangle Mediation.

### ISSUE THREAD

**Issue by funyamora** [distriqt/ANE-Adverts-Mediation#56]
Packaging fails when I try to use the latest "com.distriqt.admob.Pangle" 4.9.0.

##### Environment 

- AIR SDK version: 33.1.1.935
- Device OS:  iOS 16.2
- Device version: iPhone 14 Plus
- Development IDE: IntelliJ IDEA 2022.3.1 (Ultimate Edition)
- Development OS: macOS 13.1

- com.distriqt.admob.Pangle: 4.9.0

##### Logs

```Undefined symbols for architecture arm64: "_OBJC_CLASS_$_DCDevice", referenced from: objc-class-ref in PAGAdSDK(libMetaSecOV.a-arm64-master.o) ld: symbol(s) not found for architecture arm64 Compilation failed while executing : ld64```

**Comment by funyamora** [comment]
I've tried the latest ANE, but the problem persists.
I suspect that DeviceCheck.framework is not included in the ANE build.
Could you please check again?

**Comment by marchbold** [comment]
Thanks for reporting this, we'll look into it.

**Comment by marchbold** [comment]
Looks like you are correct, we missed a dependency. Unfortunately our tests missed it, were incorrectly configured to run on an old version. I've got an update in process now.
