### ISSUE TITLE
Paid Event Handler returns no real revenues for rewarded videos with admob

### ISSUE THREAD

**Issue by spielepalast** [distriqt/ANE-Adverts-Mediation#57]
If you are reporting a bug please make sure you fill out the following information, otherwise delete this template and ask your question.

##### Expected behaviour

The Paid Event Handler should return real revenues for rewarded videos with admob like 0.001 USD

##### Actual behaviour

The Paid Event Handler returns for rewarded videos with admob "1 Reward", where '1' is the value and 'Reward' is the currencyCode. Those are the values that we have configured in the admob dashboard as a reward if the user watches the video.

##### Environment 

- AIR SDK version: 33.1.1.935
- Device OS: android and ios
- Device version: irrelevant
- Development IDE: irrelevant 
- Development OS: irrelevant

##### Logs

Device logs if relevant

**Comment by marchbold** [comment]
Hi, we are just returning the value the SDK provides, there is no other information provided. The value is the from the `getValueMicros()` :

> The ad's value in micro-units, where 1,000,000 micro-units equal one unit of the currency


https://developers.google.com/android/reference/com/google/android/gms/ads/AdValue
