### ISSUE TITLE
[iOS] ITMS-90482: Invalid Executable - 'FBAudienceNetwork' contains bitcode.

### ISSUE THREAD

**Issue by megajogos** [distriqt/ANE-Adverts-Mediation#58]
We are receiving the following error from AppleStore:

ITMS-90482: Invalid Executable - The executable 'MegaJogos.app/Frameworks/FBAudienceNetwork.framework/FBAudienceNetwork' contains **bitcode.**

Our app was not accepted to the Store because of this problem.

**Comment by marchbold** [comment]
What version of the Facebook extension are you using? I believe the latest version should have resolved this issue

**Comment by marchbold** [comment]
I'll double check the facebook audience sdk version we are using.

**Comment by megajogos** [comment]
@marchbold please remove the Bitcode from this framework!

**Comment by megajogos** [comment]
Workaround:

Execute the command "xcrun bitcode_strip -r Frameworks/FBAudienceNetwork.framework/FBAudienceNetwork -o Frameworks/FBAudienceNetwork.framework/FBAudienceNetwork"

**Comment by marchbold** [comment]
Yes, we have created an updated build script to do this for frameworks that haven't been updated as yet. We are just testing it's effects.

**Comment by marchbold** [comment]
Update should be available now, let me know if you run into any issues.
