### ISSUE TITLE
Error initializing Pangle Android lib

### ISSUE THREAD

**Issue by megajogos** [distriqt/ANE-Adverts-Mediation#63]
When initializing Ads mediations in the application it causes an error in the Pangle lib

[log_cat_pangle_error.txt](https://github.com/distriqt/ANE-Adverts-Mediation/files/13058430/log_cat_pangle_error.txt)

**Comment by marchbold** [comment]
Did you include the pangle mediation adapter in your build? Looks like it can't find it?

**Comment by megajogos** [comment]
Yes, the lib is included. On iOS it is working fine, only on Android it stopped working.

Attached is the AndroidManifest and our extensions used:
[app.txt](https://github.com/distriqt/ANE-Adverts-Mediation/files/13073880/app.txt)
[AndroidManifest.txt](https://github.com/distriqt/ANE-Adverts-Mediation/files/13073897/AndroidManifest.txt)

**Comment by marchbold** [comment]
What versions of the extensions are you using? Adverts and pangle mediator in particular?

**Comment by megajogos** [comment]
The Adverts is in 14.3.0 and Pangle is in 4.9.2

**Comment by megajogos** [comment]
Do you have any update about this?

**Comment by marchbold** [comment]
This should be resolved in the latest releases, but let me know if you are still having issues.
