### ISSUE TITLE
Using APM adds Ironsource dependencies and mediation dependencies

### ISSUE THREAD

**Issue by yvant** [distriqt/ANE-Adverts-Mediation#64]
I used APM to install Ironsource mediation with
> apm install com.distriqt.admob.IronSource

and generated the application.xml with 
> apm generate app-descriptor

but the application.xml added some additionnal dependencies like:
    <extensionID>com.distriqt.IronSource</extensionID>
    <extensionID>com.distriqt.ironsource.AdMob</extensionID>
    <extensionID>com.google.guava</extensionID>

The compilation failed because of them, so I removed them and now it's working. So apparently APM shouldn't add these lines.
Here are my dependencies btw:
├──com.distriqt.admob.IronSource@7.4.1
├──com.distriqt.Adverts@14.3.0
├──com.distriqt.ApplicationRater@6.3.2
├──com.distriqt.facebook.Core@16.0.103
├──com.distriqt.Firebase@8.0.1
├──com.distriqt.firebase.Crashlytics@8.0.1
├──com.distriqt.GameServices@8.3.0
├──com.distriqt.InAppBilling@15.2.1
├──com.distriqt.Notifications@6.6.4
├──com.distriqt.PackageManager@3.4.0
├──com.distriqt.playservices.Licensing@1.0.84
└──com.distriqt.Share@7.6.0

**Comment by marchbold** [comment]
Can you share the project and project lock files that caused this?

**Comment by yvant** [comment]
Yes, here they are:
[project.txt](https://github.com/distriqt/ANE-Adverts-Mediation/files/13895736/project.txt)
[project-lock.txt](https://github.com/distriqt/ANE-Adverts-Mediation/files/13895737/project-lock.txt)

**Comment by marchbold** [comment]
@yvant I can't seem to replicate any issues here. It is possible that you have a cache that hasn't been cleaned up correctly (perhaps an interrupted update / uninstall)

Try deleting the `project-lock.apm` file, the `apm_packages` directory and the `ane` directory then running `apm install` again.
