### ISSUE TITLE
minsdk error when generating app descriptor

### ISSUE THREAD

**Issue by Kelsonk** [distriqt/ANE-Adverts-Mediation#68]
Updated all ANE's today and got this error when trying to generate a new app descriptor

uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library C:\Users\kelso\OneDrive\Desktop\castleclickNew\apm\apm_packages\com.distriqt.playservices.Base\contents\platforms\android\AndroidManifest.xml as the library might be using APIs not available in 21
        Suggestion: use a compatible library with a minSdk of at most 21,
                or increase this project's minSdk version to at least 24,
                or use tools:overrideLibrary="com.distriqt.extension.playservices.base" to force usage (may lead to runtime failures)

**Comment by Kelsonk** [comment]
> Thanks @Kelsonk. We are in process of updating the admob mediators, I believe your conflict will be from the `com.distriqt.admob.UnityAds` mediator. I'll make this a priority and get an update out shortly.

After a lot of trial and error I've determined that the Firebase performance and crashlytics anes are also a problem, not sure if it's just one or both.

**Comment by marchbold** [comment]
Yes so the firebase performance and crashlytics likely have the newer version, the mediators have the older version and causing the conflict. You could remove either and resolve the conflict.

**Comment by Kelsonk** [comment]
> All the mediators have been updated, let me know if you have any further issues with the okio conflict

Getting this now, all apms are updated 

java.io.IOException: Unable to run java: com.adobe.air.ADTException: gradle tool failed:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     C:\Users\kelso\AppData\Local\Temp\4f9c284f-d151-46cd-8e84-7b7f74cdb367\app\build\intermediates\packaged_manifests\release\AndroidManifest.xml:199: error: resource xml/distriqt_notifications_paths (aka air.com.snowflake.CasteClicker:xml/distriqt_notifications_paths) not found.
     C:\Users\kelso\AppData\Local\Temp\4f9c284f-d151-46cd-8e84-7b7f74cdb367\app\build\intermediates\packaged_manifests\release\AndroidManifest.xml:209: error: resource integer/google_play_services_version (aka air.com.snowflake.CasteClicker:integer/google_play_services_version) not found.
     C:\Users\kelso\AppData\Local\Temp\4f9c284f-d151-46cd-8e84-7b7f74cdb367\app\build\intermediates\packaged_manifests\release\AndroidManifest.xml:345: error: resource style/Theme.PlayCore.Transparent (aka air.com.snowflake.CasteClicker:style/Theme.PlayCore.Transparent) not found.
     error: failed processing manifest.

├──androidx.cardview@1.0.6
├──com.distriqt.admob.AppLovin@12.5.0
├──com.distriqt.admob.IronSource@8.1.0
├──com.distriqt.admob.UnityAds@4.11.300
├──com.distriqt.Adverts@15.1.0
├──com.distriqt.Application@7.1.0
├──com.distriqt.Dialog@8.8.0
├──com.distriqt.Firebase@9.0.1
├──com.distriqt.firebase.Crashlytics@9.0.1
├──com.distriqt.firebase.Performance@9.0.1
├──com.distriqt.IDFA@5.2.0
├──com.distriqt.InAppBilling-Amazon@15.4.0
├──com.distriqt.Notifications@6.7.0
├──com.distriqt.playservices.Analytics@18.0.303
└──com.google.android.material@1.6.4

**Comment by Kelsonk** [comment]
> All the mediators have been updated, let me know if you have any further issues with the okio conflict

Works great, thanks

**Comment by marchbold** [comment]
Brilliant, thanks for letting me know!

**Comment by Kelsonk** [comment]
> Brilliant, thanks for letting me know!

Not sure where to put this or if it's even an Ane issue but I'm getting a lot of crashes on iOS on my newest version, posted below. This crash does NOT happen on my test device, I'll check which version my iPad is running when I get home. 

{"app_name":"CastleClicker","timestamp":"2024-06-04 01:25:22.00 +0100","app_version":"4.6.965","slice_uuid":"4c4c44cd-5555-3144-a1c0-9ff1dba23446","adam_id":"1426921778","build_version":"4.6.965","platform":2,"bundleID":"com.autotelic.castleclicker","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 16.7.8 (20H343)","roots_installed":0,"name":"CastleClicker","incident_id":"67F1D93A-AEE2-4DEF-86B9-3B5E68875A66"}
{
  "uptime" : 440000,
  "procRole" : "unknown",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPad6,11",
  "coalitionID" : 505,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 16.7.8",
    "releaseType" : "User",
    "build" : "20H343"
  },
  "captureTime" : "2024-06-04 01:25:19.6094 +0100",
  "incident" : "67F1D93A-AEE2-4DEF-86B9-3B5E68875A66",
  "pid" : 9866,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-06-04 01:25:19.5041 +0100",
  "procStartAbsTime" : 10759473016870,
  "procExitAbsTime" : 10759474979349,
  "procName" : "CastleClicker",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/1E6F57BE-850D-4CCF-9B0C-78AEF4E25EC9\/CastleClicker.app\/CastleClicker",
  "bundleInfo" : {"CFBundleShortVersionString":"4.6.965","CFBundleVersion":"4.6.965","CFBundleIdentifier":"com.autotelic.castleclicker","DTAppStoreToolsBuild":"15F31e"},
  "storeInfo" : {"storeCohortMetadata":"10|date=1715603400000&sf=143444&pgtp=Search&pgid=5a28d60a-bedc-4e8f-a57c-18d10d3eb8f9&prpg=SearchLanding_SearchLanding&ctxt=Search&issrch=1&imptyp=card&kind=iosSoftware&lngid=2","itemID":"1426921778","deviceIdentifierForVendor":"9DB45763-DE6B-4881-81D5-620D3F62EDB1","softwareVersionExternalIdentifier":"866357688","thirdParty":true,"applicationVariant":"1:iPad6,11:15"},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.autotelic.castleclicker",
  "crashReporterKey" : "58e6661464f2a3f84ca93816c84c3921addd52be",
  "wasUnlockedSinceBoot" : 1,
  "isLocked" : 0,
  "codeSigningID" : "com.autotelic.castleclicker",
  "codeSigningTeamID" : "8GML6J39M4",
  "codeSigningFlags" : 570450689,
  "codeSigningValidationCategory" : 4,
  "codeSigningTrustLevel" : 0,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":4,"flags":518,"namespace":"DYLD","indicator":"Symbol missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Symbol not found: _$s7Network11NWInterfaceV13InterfaceTypeO8cellularyA2EmFWC","Referenced from: <4C4C44CD-5555-3144-A1C0-9FF1DBA23446> \/Volumes\/VOLUME\/*\/CastleClicker.app\/CastleClicker","Expected in:     <27116225-7C3D-3550-B844-66BE3A55F668> \/System\/Library\/Frameworks\/Network.framework\/Network"]},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":1453186,"threadState":{"x":[{"value":6},{"value":4},{"value":6126534160},{"value":244},{"value":6126533136},{"value":0},{"value":0},{"value":1600},{"value":32},{"value":9},{"value":8031999980899288623},{"value":8607616174289808242},{"value":7299824218784558967},{"value":8243327206964557684},{"value":3416950565360725345},{"value":30243645579093326},{"value":521},{"value":404},{"value":0},{"value":0},{"value":6126533136},{"value":244},{"value":6126534160},{"value":4},{"value":6},{"value":5880},{"value":1},{"value":8083297688,"symbolLocation":0,"symbol":"_NSConcreteStackBlock"},{"value":6126542144}],"flavor":"ARM_THREAD_STATE64","lr":{"value":7128378316},"cpsr":{"value":0},"fp":{"value":6126533088},"sp":{"value":6126533024},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":7128338148,"matchesCrashFrame":1},"far":{"value":0}},"frames":[{"imageOffset":413412,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":1},{"imageOffset":453580,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":100,"imageIndex":1},{"imageOffset":453628,"symbol":"abort_with_payload","symbolLocation":12,"imageIndex":1},{"imageOffset":98076,"symbol":"dyld4::halt(char const*)","symbolLocation":324,"imageIndex":1},{"imageOffset":91240,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3540,"imageIndex":1},{"imageOffset":82656,"symbol":"start","symbolLocation":1760,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4340334592,
    "size" : 33210368,
    "uuid" : "4c4c44cd-5555-3144-a1c0-9ff1dba23446",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/1E6F57BE-850D-4CCF-9B0C-78AEF4E25EC9\/CastleClicker.app\/CastleClicker",
    "name" : "CastleClicker"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 7127924736,
    "size" : 510172,
    "uuid" : "8a4b89b7-d348-375b-97b1-fc8a84e3e5ce",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 6518210560,
  "size" : 2809593856,
  "uuid" : "1017d7b0-1680-37c0-8c31-076d060d9a3f"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=1552K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1552K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                         16K        1 \nStack                             1008K        1 \nVM_ALLOCATE                         16K        1 \n__CTF                               824        1 \n__DATA                            18.1M      715 \n__DATA_CONST                      68.7M      730 \n__DATA_DIRTY                      8123K      683 \n__FONT_DATA                          4K        1 \n__INFO_FILTER                         8        1 \n__LINKEDIT                       311.7M        2 \n__OBJC_RO                         79.3M        1 \n__OBJC_RW                         2432K        2 \n__TEXT                           723.9M      738 \ndyld private memory                272K        2 \n===========                     =======  ======= \nTOTAL                              1.2G     2879 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "fcb1942a4716e68a07d3498dd00c63c7b220127d",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "645c2d2f9e69a025b0a37e29",
      "factorPackIds" : {

      },
      "deploymentId" : 240000003
    },
    {
      "rolloutId" : "6112d17137f5d11121dcd4e2",
      "factorPackIds" : {

      },
      "deploymentId" : 240000560
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "d7260174-4809-4caf-897e-143b3811db72",
      "experimentId" : "64a6ffb205dfd5094f195306",
      "deploymentId" : 400000026
    }
  ]
}
}

**Comment by marchbold** [comment]
@Kelsonk Looks like that may be related to this issue: https://github.com/distriqt/ANE-Adverts-Mediation/issues/69 Could you try the update for the unity ads mediator in that issue and let me know if it resolves the issue?

**Comment by Kelsonk** [comment]
> @Kelsonk Looks like that may be related to this issue: #69 Could you try the update for the unity ads mediator in that issue and let me know if it resolves the issue?

I can do it in a bit but I just have to release a new update and pray. Maybe I can downgrade my iPad OS to replicate the crash.
