### ISSUE TITLE
Facebook Audience not working [Android]

### ISSUE THREAD

**Issue by maxddd23** [distriqt/ANE-Adverts-Mediation#70]
Facebook Audience is not working on Android.

Did I miss something?

Please help me, thank you.

- AIR SDK version: 50.2.5.1
- Device OS: Andriod 12
- Development IDE: FlashDevelop
- Development OS:Windows 10

##### Logs
[log.txt](https://github.com/user-attachments/files/15516582/log.txt)

![1717173914565](https://github.com/distriqt/ANE-Adverts-Mediation/assets/84710126/d5fec787-1a24-4632-bbb0-030bb9e49aee)

**Comment by marchbold** [comment]
Can you elaborate some more on what's not working and how you are testing? I can't see any errors in the logs, did you double check your manifest is correct?

**Comment by maxddd23** [comment]
I set up the Banner of Meta Audience Network, but it always fails to display.

It is marked as valid in the ADMOB background
![admob](https://github.com/distriqt/ANE-Adverts-Mediation/assets/84710126/49ae6b8c-7c12-4952-9a24-105260449d7e)

However, META's background always shows that it is waiting for bidding or that no bidding request has been received yet.
![1717468830487](https://github.com/distriqt/ANE-Adverts-Mediation/assets/84710126/bae11a51-2866-4d07-914b-593755ff7f0b)

The following is the code I wrote according to the document. I am not sure where the error occurred.
![1717469327243](https://github.com/distriqt/ANE-Adverts-Mediation/assets/84710126/36ffde05-dc1d-4abb-8da5-7399e4ab5b4a)

Please help me,thank you.

**Comment by marchbold** [comment]
The extensions have been updated to the latest SDK, could you update to the latest release and let us know if you are still encountering this issue?

**Comment by maxddd23** [comment]
We no longer use this feature.

Now only using ADMOB ANE.

FACEBOOK related background functions have been closed.

So sorry, I can't test it.

Thank you for your support.

**Comment by marchbold** [comment]
Thanks for letting me know.
