### ISSUE TITLE
UnityAds crash on iOS 15

### ISSUE THREAD

**Issue by marchbold** [distriqt/ANE-Adverts-Mediation#71]
@marchbold It is not resolved even with the latest release v7.0.1.
The situation remains the same, and it crashes when I run the sample project UnityAdsTests#init.
This always occurs on iOS15, but there is no problem on iOS17.
https://github.com/distriqt/ANE-Adverts-Mediation/issues/69#issuecomment-2151535401

Here are the logs and apm.
[apm_and_logs.zip](https://github.com/user-attachments/files/15813989/apm_and_logs.zip)

_Originally posted by @funyamora in https://github.com/distriqt/ANE-Adverts-Mediation/issues/69#issuecomment-2164387186_

**Comment by marchbold** [comment]
Just an update here, we have been able to replicate this on a 15.8.2 device. Unfortunately it seems to be something internal to the unitysdk that I can't track down. I'll have to spend some more time investigating. 

Have you been able to replicate this on any other iOS version seems to be something with 15.x?

**Comment by funyamora** [comment]
So it was a problem with Unity SDK. I understand. I'll try something other than UnityAds. Thank you for your investigation.

Currently, the issue is only observed on iOS 15.8.2.

**Comment by cleverbeapps** [comment]
@marchbold Today, I received an email from Unity stating that they have fixed Unity Ads. Can we have a new update of ANE-Adverts-Mediation including this fix soon?

**Comment by marchbold** [comment]
@cleverbeapps Thanks for the update, I'll get the latest SDK update into our schedule.

**Comment by marchbold** [comment]
Hi, The latest update seems to resolve this issue in our testing. Let us know how it goes. 

Please note with the latest AIR SDK we have had to specify the platformsdk and point to a recent version of the iOS SDK in order to get around a crash at launch. If you find your application is now crashing at launch try using a recent iOS SDK when building.
