### ISSUE TITLE
Add Liftoff Monetize (Vungle) mediation network

### ISSUE THREAD

**Issue by marchbold** [distriqt/ANE-Adverts-Mediation#75]
- iOS: https://developers.google.com/admob/ios/mediation/liftoff-monetize
- Android: https://developers.google.com/admob/android/mediation/liftoff-monetize

**Comment by Coinlogru** [comment]
Manual page are missed: https://docs.airnativeextensions.com/docs/adverts/mediation/vungle
Which activity and provider tags should I add in manifest for Vungle?
What libraries and ANE should I import?
