### ISSUE TITLE
 Duplicate class okio.*

### ISSUE THREAD

**Issue by SponsorAds** [distriqt/ANE-Adverts-Mediation#76]
Newest ANE versions, just downloaded.

Adding **androidx.datastore** to the exentsions, as demanded by documentation for UnityAds mediation, results in the error from title.

My full extension list (datastore excluded):

>     <extensionID>io.grpc</extensionID>
>     <extensionID>com.distriqt.Notifications</extensionID>
>     <extensionID>com.distriqt.IDFA</extensionID>
>     <extensionID>androidx.room</extensionID>
>     <extensionID>com.distriqt.facebook.Share</extensionID>
>     <extensionID>com.android.installreferrer</extensionID>
>     <extensionID>androidx.core</extensionID>
>     <extensionID>androidx.cardview</extensionID>
>     <extensionID>androidx.exifinterface</extensionID>
>     <extensionID>com.distriqt.playservices.Ads</extensionID>
>     <extensionID>com.distriqt.InAppBilling</extensionID>
>     <extensionID>androidx.vectordrawable</extensionID>
>     <extensionID>androidx.emoji2</extensionID>
>     <extensionID>com.google.android.play</extensionID>
>     <extensionID>com.bumptech.glide</extensionID>
>     <extensionID>com.distriqt.Bolts</extensionID>
>     <extensionID>com.distriqt.Firebase</extensionID>
>     <extensionID>com.distriqt.playservices.Base</extensionID>
>     <extensionID>com.distriqt.Volume</extensionID>
>     <extensionID>com.distriqt.Adverts</extensionID>
>     <extensionID>com.jetbrains.kotlin</extensionID>
>     <extensionID>com.google.protobuflite</extensionID>
>     <extensionID>com.google.code.gson</extensionID>
>     <extensionID>com.distriqt.playservices.AdsIdentifier</extensionID>
>     <extensionID>com.google.dagger</extensionID>
>     <extensionID>com.distriqt.admob.FacebookAudience</extensionID>
>     <extensionID>com.distriqt.Application</extensionID>
>     <extensionID>androidx.browser</extensionID>
>     <extensionID>androidx.appcompat</extensionID>
>     <extensionID>com.distriqt.square.okhttp</extensionID>
>     <extensionID>com.distriqt.admob.AppLovin</extensionID>
>     <extensionID>androidx.work</extensionID>
>     <extensionID>com.google.android.datatransport</extensionID>
>     <extensionID>com.distriqt.Core</extensionID>
>     <extensionID>com.distriqt.NetworkInfo</extensionID>
>     <extensionID>com.google.firebase.core</extensionID>
>     <extensionID>com.distriqt.MediaPlayer</extensionID>
>     <extensionID>com.distriqt.playservices.CloudMessaging</extensionID>
>     <extensionID>com.distriqt.admob.UnityAds</extensionID>
>     <extensionID>com.distriqt.ZipUtils</extensionID>
>     <extensionID>com.distriqt.playservices.AppSet</extensionID>
>     <extensionID>io.reactivex</extensionID>
>     <extensionID>com.distriqt.square.okhttp3</extensionID>
>     <extensionID>com.distriqt.firebase.RemoteConfig</extensionID>
>     <extensionID>com.distriqt.facebook.Core</extensionID>
>     <extensionID>androidx.constraintlayout</extensionID>
>     <extensionID>com.distriqt.PushNotifications</extensionID>
>     <extensionID>com.google.guava</extensionID>
>     <extensionID>com.distriqt.admob.IronSource</extensionID>
>     <extensionID>com.distriqt.CustomResources</extensionID>
>     <extensionID>androidx.webkit</extensionID>
>     <extensionID>com.distriqt.playservices.Cronet</extensionID>
>     <extensionID>org.jacoco</extensionID>
>     <extensionID>org.ow2.asm</extensionID>
>

**Comment by marchbold** [comment]
Can you double check you have the latest square libs in your project?
