### ISSUE TITLE
Pangle library update

### ISSUE THREAD

**Issue by megajogos** [distriqt/ANE-Adverts-Mediation#77]
We are currently experiencing an issue with displaying ads for this mediation, so we have contacted the company responsible for Pangle and they have asked us to update to version 6.2.0.5. Would it be possible to do this update?

Thanks

**Comment by marchbold** [comment]
Yes, will get this into development.

**Comment by marchbold** [comment]
Here is a beta release of the pangle mediator.

https://drive.google.com/file/d/1-JFG8UCMIiLMNrqzA1V6smqrssywPMD8/view?usp=sharing

If you have some time, we would appreciate any feedback.
