### ISSUE TITLE
[Feature Request] - Facebook ads / Mediation integrate

### ISSUE THREAD

**Issue by leossmith** [distriqt/ANE-Adverts-Mediation#8]
Please add Facebook Audience Ads mediation. This should include support for banner, interstitial and video ads.

**Comment by marchbold** [comment]
We actually just added Facebook mediation this evening with the Android X update:

https://github.com/distriqt/ANE-Adverts-Mediation/tree/master/lib/facebookaudience

Please wait until the Android X migration is complete though before attempting to use the new extensions.

**Comment by leossmith** [comment]
Awesome,

thanks.
