### ISSUE TITLE
AppLovin for iOS

### ISSUE THREAD

**Issue by 2cde** [distriqt/ANE-Adverts-Mediation#9]
Hi,

I could not find how to integrate the AppLovin SDK into an iOS app on the Wiki page. Doesn't this ANE support for iOS?

**Comment by marchbold** [comment]
Currently the applovin mediator is only for Android.

**Comment by 2cde** [comment]
Okay. Thank you for your quick response.

**Comment by marchbold** [comment]
I'll get this into development for you though, so let's leave this open.

**Comment by 2cde** [comment]
Thank you. I really appreciate it.

**Comment by marchbold** [comment]
Just pushing this update into the repository, let me know if you have any issues.

**Comment by 2cde** [comment]
Wow, thank you so much! I'll test this soon!

**Comment by marchbold** [comment]
Cheers, please let us know if you run into any issues!
